---
- name: Install Docker
  hosts: all
  gather_facts: true
  become: true

  vars_files:
    - ../secrets/secrets.yml

  vars:
    ansible_connection: "{{ ANSIBLE_CONNECTION | default('aws_ssm') }}"
    # Architecture mapping for Docker repo (Robust against aarch64/x86_64 differences)
    arch_mapping:
      x86_64: amd64
      aarch64: arm64

  tasks:
    - name: Wait for connection
      ansible.builtin.wait_for_connection:
        timeout: 300

    - name: Install prerequisites packages
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: true

    - name: Ensure Keyrings path exists
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Docker official GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'
      register: docker_gpg_key

    # FIX: Only dearmor if the key changed or the binary doesn't exist. 
    # '--yes' forces overwrite if needed.
    - name: Convert Docker GPG key to binary keyring
      ansible.builtin.command:
        cmd: gpg --dearmor --yes -o /etc/apt/keyrings/docker.gpg /etc/apt/keyrings/docker.asc
      when: docker_gpg_key.changed or ansible_check_mode
      # This ensures the task doesn't report 'changed' unnecessarily on subsequent runs
      changed_when: docker_gpg_key.changed

    - name: Ensure permissions on Docker GPG key
      ansible.builtin.file:
        path: /etc/apt/keyrings/docker.gpg
        mode: '0644'

    - name: Add Docker APT repository
      ansible.builtin.apt_repository:
        repo: >
          deb [arch={{ arch_mapping[ansible_architecture] | default('amd64') }} signed-by=/etc/apt/keyrings/docker.gpg]
          https://download.docker.com/linux/ubuntu
          {{ ansible_distribution_release }} stable
        state: present
        filename: docker

    - name: Install Docker Engine packages
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: true