name: Infrastructure Provisioning
on:
  repository_dispatch:
    types: [event-provision-infra]

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform 

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Create Variables File
        run: |
          cat <<EOF > terraform.tfvars.json
          {
            "ui_manifest": ${{ toJson(github.event.client_payload.manifest) }}
          }
          EOF

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=daaa-r6e3a9" \
            -backend-config="key=projects/infra.tfstate" \
            -backend-config="region=${{ secrets.AWS_DEFAULT_REGION }}" \
            -backend-config="encrypt=true"

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Action (Apply or Destroy)
        # Use the tf_action from the UI payload, default to 'apply' if not sent
        run: |
          ACTION="${{ github.event.client_payload.tf_action }}"
          if [ "$ACTION" == "destroy" ]; then
            terraform destroy -auto-approve
          else
            terraform apply -auto-approve
          fi

      - name: Identify Requested Services
        if: github.event.client_payload.tf_action != 'destroy'
        id: service_check
        run: |
          DOCKER_REQ=$(jq '[.ui_manifest[].subnets[].resources[] | select(.type=="EC2").instances[].services[] | select(. == "Docker")] | length > 0' terraform.tfvars.json)
          NGINX_REQ=$(jq '[.ui_manifest[].subnets[].resources[] | select(.type=="EC2").instances[].services[] | select(. == "NGINX")] | length > 0' terraform.tfvars.json)
          MINIKUBE_REQ=$(jq '[.ui_manifest[].subnets[].resources[] | select(.type=="EC2").instances[].services[] | select(. == "MiniKube")] | length > 0' terraform.tfvars.json)
          
          echo "run_docker=$DOCKER_REQ" >> $GITHUB_OUTPUT
          echo "run_nginx=$NGINX_REQ" >> $GITHUB_OUTPUT
          echo "run_minikube=$MINIKUBE_REQ" >> $GITHUB_OUTPUT

      # Playbooks only run during 'apply'
      - name: Run Docker Installation
        if: github.event.client_payload.tf_action != 'destroy' && steps.service_check.outputs.run_docker == 'true'
        run: echo "Running docker installation"

      - name: Run Nginx Installation
        if: github.event.client_payload.tf_action != 'destroy' && steps.service_check.outputs.run_nginx == 'true'
        run: echo "Running nginx installation"

      - name: Run MiniKube Installation
        if: github.event.client_payload.tf_action != 'destroy' && steps.service_check.outputs.run_minikube == 'true'
        run: echo "Running minikube installation"